import {Inter,Poppins} from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Delivery All',
  description: 'Generated by Next.js',
}

// Load Inter
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // Optional: Custom CSS variable
});

// Load Poppins
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'], // Specify needed weights
  variable: '--font-poppins', // Optional: Custom CSS variable
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  className={`${inter.variable} ${poppins.variable}`}>
      <body>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
